[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
bincode = "2.0.1"
smol = "2.0.2"
winsafe = { version = "0.0.25", features = ["user"] }
aes-gcm = "0.10.3"
image = { version = "0.25.6", features = ["webp"] }
xcap = "0.6.2"
webp = "0.3.0"
